# Generated by Django 3.0.4 on 2020-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='created_on',
            new_name='createdon',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='completed_on',
        ),
        migrations.AddField(
            model_name='todos',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
