# Generated by Django 3.0.4 on 2020-04-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200404_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
